
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN DIVIDE ID LPAREN MINUS NUMBER PLUS RPAREN SEMI TIMESprogram : assignmentprogram : assignment programassignment : ID ASSIGN expression SEMIexpression : expression PLUS termexpression : expression MINUS termexpression : termterm : term TIMES factorterm : term DIVIDE factorterm : factorfactor : NUMBERfactor : IDfactor : LPAREN expression RPAREN'
    
_lr_action_items = {'ID':([0,2,5,11,12,13,14,15,16,],[3,3,6,6,-3,6,6,6,6,]),'$end':([1,2,4,12,],[0,-1,-2,-3,]),'ASSIGN':([3,],[5,]),'NUMBER':([5,11,13,14,15,16,],[10,10,10,10,10,10,]),'LPAREN':([5,11,13,14,15,16,],[11,11,11,11,11,11,]),'TIMES':([6,8,9,10,18,19,20,21,22,],[-11,15,-9,-10,15,15,-7,-8,-12,]),'DIVIDE':([6,8,9,10,18,19,20,21,22,],[-11,16,-9,-10,16,16,-7,-8,-12,]),'SEMI':([6,7,8,9,10,18,19,20,21,22,],[-11,12,-6,-9,-10,-4,-5,-7,-8,-12,]),'PLUS':([6,7,8,9,10,17,18,19,20,21,22,],[-11,13,-6,-9,-10,13,-4,-5,-7,-8,-12,]),'MINUS':([6,7,8,9,10,17,18,19,20,21,22,],[-11,14,-6,-9,-10,14,-4,-5,-7,-8,-12,]),'RPAREN':([6,8,9,10,17,18,19,20,21,22,],[-11,-6,-9,-10,22,-4,-5,-7,-8,-12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,2,],[1,4,]),'assignment':([0,2,],[2,2,]),'expression':([5,11,],[7,17,]),'term':([5,11,13,14,],[8,8,18,19,]),'factor':([5,11,13,14,15,16,],[9,9,9,9,20,21,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> assignment','program',1,'p_program_single','main.py',58),
  ('program -> assignment program','program',2,'p_program_multiple','main.py',63),
  ('assignment -> ID ASSIGN expression SEMI','assignment',4,'p_assignment','main.py',68),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','main.py',74),
  ('expression -> expression MINUS term','expression',3,'p_expression_minus','main.py',78),
  ('expression -> term','expression',1,'p_expression_term','main.py',82),
  ('term -> term TIMES factor','term',3,'p_term_times','main.py',87),
  ('term -> term DIVIDE factor','term',3,'p_term_divide','main.py',91),
  ('term -> factor','term',1,'p_term_factor','main.py',95),
  ('factor -> NUMBER','factor',1,'p_factor_number','main.py',100),
  ('factor -> ID','factor',1,'p_factor_id','main.py',104),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','main.py',108),
]
